apiVersion: apps/v1
kind: Deployment
metadata:
  name: devtron-java
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devtron-java
  template:
    metadata:
      labels:
        app: devtron-java
    spec:
      containers:
        - name: devtron-java
          image: devtron-java:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: '1'

---
apiVersion: v1
kind: Service
metadata:
  name: devtron-java-balancer
spec:
  selector:
    app: devtron-java
  ports:
    - protocol: TCP
      port: 8000 # The port to expose to the outside
      targetPort: 8080 # The port the application is running on in the pods
  type: LoadBalancer
  sessionAffinity: ClientIP
